#!/usr/bin/env python

import argparse
import os
import openai

openai.api_key = os.environ['OPENAI_API_KEY']

PROMPT = "You're an expert sys admin, what is the answer to this question that will run on a mac m1 on zsh \n\n --- question start ---- \n\n  {query} \n\n  --- question end --- show with code:"

def query(q):
    prompt = PROMPT.format(query=q)

    response = openai.ChatCompletion.create(
        model='gpt-3.5-turbo',
        messages=[
            {
                'role': 'user',
                'content': prompt
            }
        ],
        max_tokens=250,
        temperature=0,
        stream=True
    )

    for event in response:
        delta = event['choices'][0]['delta']
        if 'content' not in delta:
            continue
        event_text = delta['content']
        print(event_text, end="", flush=True)
    print()


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('q', help="The programming question")
    args = parser.parse_args()
    query(args.q)
